---
title: "R Notebook"
output: html_notebook
---


```{r}
library(dplyr)
library(ggplot2)
library(scales)
a <- read.delim(file = "x.txt",encoding='UTF-8',header = FALSE)
bst <- read.delim(file = "bst.txt",encoding='UTF-8',header = FALSE)
rbt <- read.delim(file = "rbt.txt",encoding='UTF-8',header = FALSE)
avl <- read.delim(file = "avl.txt",encoding='UTF-8',header = FALSE)

data <- data.frame(
  a,bst,rbt,avl
)
names(data) = c("x","bst","rbt","avl")

logaritmico <- ggplot(data, aes(x=x)) + 
  geom_line(aes(y = bst), color = "blue") +
  geom_point(aes(y = bst), color = "blue") +
  geom_line(aes(y = avl), color = "red") +
  geom_point(aes(y = avl), color = "red") +
  geom_line(aes(y = rbt), color="green") +
  geom_point(aes(y = rbt), color = "green") +
  scale_x_continuous(trans='log10', labels = comma) + scale_y_continuous(trans='log10', labels=comma) +
  xlab("n") + ylab("secs")

logaritmico
```
```{r}
lineare <- ggplot(data, aes(x=x)) + 
  geom_line(aes(y = bst), color = "blue") +
  geom_point(aes(y = bst), color = "blue") +
  geom_line(aes(y = avl), color = "red") +
  geom_point(aes(y = avl), color = "red") +
  geom_line(aes(y = rbt), color="green") +
  geom_point(aes(y = rbt), color = "green") +
  scale_x_continuous(labels=comma) + scale_y_continuous(labels=comma ) +
  xlab("n") + ylab("secs")
lineare
```

